# Generated by Django 3.1.6 on 2021-02-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_repassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
